# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or create!d alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create!([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create!(name: 'Luke', movie: movies.first)


Erg.create(name: 'People with Disabilities')
Erg.create(name: 'Amazon Women in Engineering')
Erg.create(name: 'Asians')
Erg.create(name: 'Black Employee Network')
Erg.create(name: 'Body Positive Peers')
Erg.create(name: 'Families@Amazon')
Erg.create(name: 'Glamazon')
Erg.create(name: 'Indigenous')
Erg.create(name: 'Latinos')
Erg.create(name: 'Warriors')
Erg.create(name: 'Women@')
Erg.create(name: 'Women in Finance Initiative')

GlobalArea.create!(name: 'Americas')
GlobalArea.create!(name: 'EMEA')

Country.create!(name: 'Afghanistan', two_letter_code: 'AF')
Country.create!(name: 'Albania', two_letter_code: 'AL')
Country.create!(name: 'Algeria', two_letter_code: 'DZ')
Country.create!(name: 'American Samoa', two_letter_code: 'AS')
Country.create!(name: 'Andorra', two_letter_code: 'AD')
Country.create!(name: 'Angola', two_letter_code: 'AO')
Country.create!(name: 'Anguilla', two_letter_code: 'AI')
Country.create!(name: 'Antarctica', two_letter_code: 'AQ')
Country.create!(name: 'Antigua and Barbuda', two_letter_code: 'AG')
Country.create!(name: 'Argentina', two_letter_code: 'AR')
Country.create!(name: 'Armenia', two_letter_code: 'AM')
Country.create!(name: 'Aruba', two_letter_code: 'AW')
Country.create!(name: 'Australia', two_letter_code: 'AU')
Country.create!(name: 'Austria', two_letter_code: 'AT')
Country.create!(name: 'Azerbaijan', two_letter_code: 'AZ')
Country.create!(name: 'Bahamas', two_letter_code: 'BS')
Country.create!(name: 'Bahrain', two_letter_code: 'BH')
Country.create!(name: 'Bangladesh', two_letter_code: 'BD')
Country.create!(name: 'Barbados', two_letter_code: 'BB')
Country.create!(name: 'Belarus', two_letter_code: 'BY')
Country.create!(name: 'Belgium', two_letter_code: 'BE')
Country.create!(name: 'Belize', two_letter_code: 'BZ')
Country.create!(name: 'Benin', two_letter_code: 'BJ')
Country.create!(name: 'Bermuda', two_letter_code: 'BM')
Country.create!(name: 'Bhutan', two_letter_code: 'BT')
Country.create!(name: 'Bosnia and Herzegovina', two_letter_code: 'BA')
Country.create!(name: 'Botswana', two_letter_code: 'BW')
Country.create!(name: 'Bouvet Island', two_letter_code: 'BV')
Country.create!(name: 'Brazil', two_letter_code: 'BR')
Country.create!(name: 'British Indian Ocean Territory', two_letter_code: 'IO')
Country.create!(name: 'Brunei Darussalam', two_letter_code: 'BN')
Country.create!(name: 'Bulgaria', two_letter_code: 'BG')
Country.create!(name: 'Burkina Faso', two_letter_code: 'BF')
Country.create!(name: 'Burundi', two_letter_code: 'BI')
Country.create!(name: 'Cambodia', two_letter_code: 'KH')
Country.create!(name: 'Cameroon', two_letter_code: 'CM')
Country.create!(name: 'Canada', two_letter_code: 'CA')
Country.create!(name: 'Cape Verde', two_letter_code: 'CV')
Country.create!(name: 'Cayman Islands', two_letter_code: 'KY')
Country.create!(name: 'Central African Republic', two_letter_code: 'CF')
Country.create!(name: 'Chad', two_letter_code: 'TD')
Country.create!(name: 'Chile', two_letter_code: 'CL')
Country.create!(name: 'China', two_letter_code: 'CN')
Country.create!(name: 'Christmas Island', two_letter_code: 'CX')
Country.create!(name: 'Cocos (Keeling) Islands', two_letter_code: 'CC')
Country.create!(name: 'Colombia', two_letter_code: 'CO')
Country.create!(name: 'Comoros', two_letter_code: 'KM')
Country.create!(name: 'Congo', two_letter_code: 'CG')
Country.create!(name: 'Cook Islands', two_letter_code: 'CK')
Country.create!(name: 'Costa Rica', two_letter_code: 'CR')
Country.create!(name: 'Croatia', two_letter_code: 'HR')
Country.create!(name: 'Cuba', two_letter_code: 'CU')
Country.create!(name: 'Cyprus', two_letter_code: 'CY')
Country.create!(name: 'Czech Republic', two_letter_code: 'CZ')
Country.create!(name: 'Denmark', two_letter_code: 'DK')
Country.create!(name: 'Djibouti', two_letter_code: 'DJ')
Country.create!(name: 'Dominica', two_letter_code: 'DM')
Country.create!(name: 'Dominican Republic', two_letter_code: 'DO')
Country.create!(name: 'Ecuador', two_letter_code: 'EC')
Country.create!(name: 'Egypt', two_letter_code: 'EG')
Country.create!(name: 'El Salvador', two_letter_code: 'SV')
Country.create!(name: 'Equatorial Guinea', two_letter_code: 'GQ')
Country.create!(name: 'Eritrea', two_letter_code: 'ER')
Country.create!(name: 'Estonia', two_letter_code: 'EE')
Country.create!(name: 'Ethiopia', two_letter_code: 'ET')
Country.create!(name: 'Falkland Islands (Malvinas)', two_letter_code: 'FK')
Country.create!(name: 'Faroe Islands', two_letter_code: 'FO')
Country.create!(name: 'Fiji', two_letter_code: 'FJ')
Country.create!(name: 'Finland', two_letter_code: 'FI')
Country.create!(name: 'France', two_letter_code: 'FR')
Country.create!(name: 'French Guiana', two_letter_code: 'GF')
Country.create!(name: 'French Polynesia', two_letter_code: 'PF')
Country.create!(name: 'French Southern Territories', two_letter_code: 'TF')
Country.create!(name: 'Gabon', two_letter_code: 'GA')
Country.create!(name: 'Gambia', two_letter_code: 'GM')
Country.create!(name: 'Georgia', two_letter_code: 'GE')
Country.create!(name: 'Germany', two_letter_code: 'DE')
Country.create!(name: 'Ghana', two_letter_code: 'GH')
Country.create!(name: 'Gibraltar', two_letter_code: 'GI')
Country.create!(name: 'Greece', two_letter_code: 'GR')
Country.create!(name: 'Greenland', two_letter_code: 'GL')
Country.create!(name: 'Grenada', two_letter_code: 'GD')
Country.create!(name: 'Guadeloupe', two_letter_code: 'GP')
Country.create!(name: 'Guam', two_letter_code: 'GU')
Country.create!(name: 'Guatemala', two_letter_code: 'GT')
Country.create!(name: 'Guernsey', two_letter_code: 'GG')
Country.create!(name: 'Guinea', two_letter_code: 'GN')
Country.create!(name: 'Guinea-Bissau', two_letter_code: 'GW')
Country.create!(name: 'Guyana', two_letter_code: 'GY')
Country.create!(name: 'Haiti', two_letter_code: 'HT')
Country.create!(name: 'Heard Island and McDonald Islands', two_letter_code: 'HM')
Country.create!(name: 'Holy See (Vatican City State)', two_letter_code: 'VA')
Country.create!(name: 'Honduras', two_letter_code: 'HN')
Country.create!(name: 'Hong Kong', two_letter_code: 'HK')
Country.create!(name: 'Hungary', two_letter_code: 'HU')
Country.create!(name: 'Iceland', two_letter_code: 'IS')
Country.create!(name: 'India', two_letter_code: 'IN')
Country.create!(name: 'Indonesia', two_letter_code: 'ID')
Country.create!(name: 'Iran', two_letter_code: 'IR')
Country.create!(name: 'Iraq', two_letter_code: 'IQ')
Country.create!(name: 'Ireland', two_letter_code: 'IE')
Country.create!(name: 'Isle of Man', two_letter_code: 'IM')
Country.create!(name: 'Israel', two_letter_code: 'IL')
Country.create!(name: 'Italy', two_letter_code: 'IT')
Country.create!(name: 'Jamaica', two_letter_code: 'JM')
Country.create!(name: 'Japan', two_letter_code: 'JP')
Country.create!(name: 'Jersey', two_letter_code: 'JE')
Country.create!(name: 'Jordan', two_letter_code: 'JO')
Country.create!(name: 'Kazakhstan', two_letter_code: 'KZ')
Country.create!(name: 'Kenya', two_letter_code: 'KE')
Country.create!(name: 'Kiribati', two_letter_code: 'KI')
Country.create!(name: 'Kuwait', two_letter_code: 'KW')
Country.create!(name: 'Kyrgyzstan', two_letter_code: 'KG')
Country.create!(name: 'Lao People\'s Democratic Republic', two_letter_code: 'LA')
Country.create!(name: 'Latvia', two_letter_code: 'LV')
Country.create!(name: 'Lebanon', two_letter_code: 'LB')
Country.create!(name: 'Lesotho', two_letter_code: 'LS')
Country.create!(name: 'Liberia', two_letter_code: 'LR')
Country.create!(name: 'Libya', two_letter_code: 'LY')
Country.create!(name: 'Liechtenstein', two_letter_code: 'LI')
Country.create!(name: 'Lithuania', two_letter_code: 'LT')
Country.create!(name: 'Luxembourg', two_letter_code: 'LU')
Country.create!(name: 'Macao', two_letter_code: 'MO')
Country.create!(name: 'Madagascar', two_letter_code: 'MG')
Country.create!(name: 'Malawi', two_letter_code: 'MW')
Country.create!(name: 'Malaysia', two_letter_code: 'MY')
Country.create!(name: 'Maldives', two_letter_code: 'MV')
Country.create!(name: 'Mali', two_letter_code: 'ML')
Country.create!(name: 'Malta', two_letter_code: 'MT')
Country.create!(name: 'Marshall Islands', two_letter_code: 'MH')
Country.create!(name: 'Martinique', two_letter_code: 'MQ')
Country.create!(name: 'Mauritania', two_letter_code: 'MR')
Country.create!(name: 'Mauritius', two_letter_code: 'MU')
Country.create!(name: 'Mayotte', two_letter_code: 'YT')
Country.create!(name: 'Mexico', two_letter_code: 'MX')
Country.create!(name: 'Monaco', two_letter_code: 'MC')
Country.create!(name: 'Mongolia', two_letter_code: 'MN')
Country.create!(name: 'Montenegro', two_letter_code: 'ME')
Country.create!(name: 'Montserrat', two_letter_code: 'MS')
Country.create!(name: 'Morocco', two_letter_code: 'MA')
Country.create!(name: 'Mozambique', two_letter_code: 'MZ')
Country.create!(name: 'Myanmar', two_letter_code: 'MM')
Country.create!(name: 'Namibia', two_letter_code: 'NA')
Country.create!(name: 'Nauru', two_letter_code: 'NR')
Country.create!(name: 'Nepal', two_letter_code: 'NP')
Country.create!(name: 'Netherlands', two_letter_code: 'NL')
Country.create!(name: 'New Caledonia', two_letter_code: 'NC')
Country.create!(name: 'New Zealand', two_letter_code: 'NZ')
Country.create!(name: 'Nicaragua', two_letter_code: 'NI')
Country.create!(name: 'Niger', two_letter_code: 'NE')
Country.create!(name: 'Nigeria', two_letter_code: 'NG')
Country.create!(name: 'Niue', two_letter_code: 'NU')
Country.create!(name: 'Norfolk Island', two_letter_code: 'NF')
Country.create!(name: 'Northern Mariana Islands', two_letter_code: 'MP')
Country.create!(name: 'Norway', two_letter_code: 'NO')
Country.create!(name: 'Oman', two_letter_code: 'OM')
Country.create!(name: 'Pakistan', two_letter_code: 'PK')
Country.create!(name: 'Palau', two_letter_code: 'PW')
Country.create!(name: 'Panama', two_letter_code: 'PA')
Country.create!(name: 'Papua New Guinea', two_letter_code: 'PG')
Country.create!(name: 'Paraguay', two_letter_code: 'PY')
Country.create!(name: 'Peru', two_letter_code: 'PE')
Country.create!(name: 'Philippines', two_letter_code: 'PH')
Country.create!(name: 'Pitcairn', two_letter_code: 'PN')
Country.create!(name: 'Poland', two_letter_code: 'PL')
Country.create!(name: 'Portugal', two_letter_code: 'PT')
Country.create!(name: 'Puerto Rico', two_letter_code: 'PR')
Country.create!(name: 'Qatar', two_letter_code: 'QA')
Country.create!(name: 'RÃ©union', two_letter_code: 'RE')
Country.create!(name: 'Romania', two_letter_code: 'RO')
Country.create!(name: 'Russian Federation', two_letter_code: 'RU')
Country.create!(name: 'Rwanda', two_letter_code: 'RW')
Country.create!(name: 'Saint BarthÃ©lemy', two_letter_code: 'BL')
Country.create!(name: 'Saint Kitts and Nevis', two_letter_code: 'KN')
Country.create!(name: 'Saint Lucia', two_letter_code: 'LC')
Country.create!(name: 'Saint Martin (French part)', two_letter_code: 'MF')
Country.create!(name: 'Saint Pierre and Miquelon', two_letter_code: 'PM')
Country.create!(name: 'Saint Vincent and the Grenadines', two_letter_code: 'VC')
Country.create!(name: 'Samoa', two_letter_code: 'WS')
Country.create!(name: 'San Marino', two_letter_code: 'SM')
Country.create!(name: 'Sao Tome and Principe', two_letter_code: 'ST')
Country.create!(name: 'Saudi Arabia', two_letter_code: 'SA')
Country.create!(name: 'Senegal', two_letter_code: 'SN')
Country.create!(name: 'Serbia', two_letter_code: 'RS')
Country.create!(name: 'Seychelles', two_letter_code: 'SC')
Country.create!(name: 'Sierra Leone', two_letter_code: 'SL')
Country.create!(name: 'Singapore', two_letter_code: 'SG')
Country.create!(name: 'Sint Maarten (Dutch part)', two_letter_code: 'SX')
Country.create!(name: 'Slovakia', two_letter_code: 'SK')
Country.create!(name: 'Slovenia', two_letter_code: 'SI')
Country.create!(name: 'Solomon Islands', two_letter_code: 'SB')
Country.create!(name: 'Somalia', two_letter_code: 'SO')
Country.create!(name: 'South Africa', two_letter_code: 'ZA')
Country.create!(name: 'South Georgia and the South Sandwich Islands', two_letter_code: 'GS')
Country.create!(name: 'South Sudan', two_letter_code: 'SS')
Country.create!(name: 'Spain', two_letter_code: 'ES')
Country.create!(name: 'Sri Lanka', two_letter_code: 'LK')
Country.create!(name: 'Sudan', two_letter_code: 'SD')
Country.create!(name: 'Suriname', two_letter_code: 'SR')
Country.create!(name: 'Svalbard and Jan Mayen', two_letter_code: 'SJ')
Country.create!(name: 'Swaziland', two_letter_code: 'SZ')
Country.create!(name: 'Sweden', two_letter_code: 'SE')
Country.create!(name: 'Switzerland', two_letter_code: 'CH')
Country.create!(name: 'Syrian Arab Republic', two_letter_code: 'SY')
Country.create!(name: 'Tajikistan', two_letter_code: 'TJ')
Country.create!(name: 'Thailand', two_letter_code: 'TH')
Country.create!(name: 'Timor-Leste', two_letter_code: 'TL')
Country.create!(name: 'Togo', two_letter_code: 'TG')
Country.create!(name: 'Tokelau', two_letter_code: 'TK')
Country.create!(name: 'Tonga', two_letter_code: 'TO')
Country.create!(name: 'Trinidad and Tobago', two_letter_code: 'TT')
Country.create!(name: 'Tunisia', two_letter_code: 'TN')
Country.create!(name: 'Turkey', two_letter_code: 'TR')
Country.create!(name: 'Turkmenistan', two_letter_code: 'TM')
Country.create!(name: 'Turks and Caicos Islands', two_letter_code: 'TC')
Country.create!(name: 'Tuvalu', two_letter_code: 'TV')
Country.create!(name: 'Uganda', two_letter_code: 'UG')
Country.create!(name: 'Ukraine', two_letter_code: 'UA')
Country.create!(name: 'United Arab Emirates', two_letter_code: 'AE')
Country.create!(name: 'United Kingdom', two_letter_code: 'GB')
Country.create!(name: 'United States', two_letter_code: 'US')
Country.create!(name: 'United States Minor Outlying Islands', two_letter_code: 'UM')
Country.create!(name: 'Uruguay', two_letter_code: 'UY')
Country.create!(name: 'Uzbekistan', two_letter_code: 'UZ')
Country.create!(name: 'Vanuatu', two_letter_code: 'VU')
Country.create!(name: 'Venezuela', two_letter_code: 'VE')
Country.create!(name: 'Viet Nam', two_letter_code: 'VN')
Country.create!(name: 'Virgin Islands, British', two_letter_code: 'VG')
Country.create!(name: 'Virgin Islands, US', two_letter_code: 'VI')
Country.create!(name: 'Wallis and Futuna', two_letter_code: 'WF')
Country.create!(name: 'Western Sahara', two_letter_code: 'EH')
Country.create!(name: 'Yemen', two_letter_code: 'YE')
Country.create!(name: 'Zambia', two_letter_code: 'ZM')
Country.create!(name: 'Zimbabwe', two_letter_code: 'ZW')

State.create!(name: 'Alabama', two_letter_code: 'AL')
State.create!(name: 'Alaska', two_letter_code: 'AK')
State.create!(name: 'American Samoa', two_letter_code: 'AS')
State.create!(name: 'Arizona', two_letter_code: 'AZ')
State.create!(name: 'Arkansas', two_letter_code: 'AR')
State.create!(name: 'California', two_letter_code: 'CA')
State.create!(name: 'Colorado', two_letter_code: 'CO')
State.create!(name: 'Connecticut', two_letter_code: 'CT')
State.create!(name: 'Delaware', two_letter_code: 'DE')
State.create!(name: 'District of Columbia', two_letter_code: 'DC')
State.create!(name: 'Federated States of Micronesia', two_letter_code: 'FM')
State.create!(name: 'Florida', two_letter_code: 'FL')
State.create!(name: 'Georgia', two_letter_code: 'GA')
State.create!(name: 'Guam', two_letter_code: 'GU')
State.create!(name: 'Hawaii', two_letter_code: 'HI')
State.create!(name: 'Idaho', two_letter_code: 'ID')
State.create!(name: 'Illinois', two_letter_code: 'IL')
State.create!(name: 'Indiana', two_letter_code: 'IN')
State.create!(name: 'Iowa', two_letter_code: 'IA')
State.create!(name: 'Kansas', two_letter_code: 'KS')
State.create!(name: 'Kentucky', two_letter_code: 'KY')
State.create!(name: 'Louisiana', two_letter_code: 'LA')
State.create!(name: 'Maine', two_letter_code: 'ME')
State.create!(name: 'Marshall Islands', two_letter_code: 'MH')
State.create!(name: 'Maryland', two_letter_code: 'MD')
State.create!(name: 'Massachusetts', two_letter_code: 'MA')
State.create!(name: 'Michigan', two_letter_code: 'MI')
State.create!(name: 'Minnesota', two_letter_code: 'MN')
State.create!(name: 'Mississippi', two_letter_code: 'MS')
State.create!(name: 'Missouri', two_letter_code: 'MO')
State.create!(name: 'Montana', two_letter_code: 'MT')
State.create!(name: 'Nebraska', two_letter_code: 'NE')
State.create!(name: 'Nevada', two_letter_code: 'NV')
State.create!(name: 'New Hampshire', two_letter_code: 'NH')
State.create!(name: 'New Jersey', two_letter_code: 'NJ')
State.create!(name: 'New Mexico', two_letter_code: 'NM')
State.create!(name: 'New York', two_letter_code: 'NY ')
State.create!(name: 'North Carolina', two_letter_code: 'NC')
State.create!(name: 'North Dakota', two_letter_code: 'ND')
State.create!(name: 'Northern Mariana Islands', two_letter_code: 'MP')
State.create!(name: 'Ohio', two_letter_code: 'OH')
State.create!(name: 'Oklahoma', two_letter_code: 'OK')
State.create!(name: 'Oregon', two_letter_code: 'OR')
State.create!(name: 'Palau', two_letter_code: 'PW')
State.create!(name: 'Pennsylvania', two_letter_code: 'PA')
State.create!(name: 'Puerto Rico', two_letter_code: 'PR')
State.create!(name: 'Rhode Island', two_letter_code: 'RI')
State.create!(name: 'South Carolina', two_letter_code: 'SC')
State.create!(name: 'South Dakota', two_letter_code: 'SD')
State.create!(name: 'Tennessee', two_letter_code: 'TN')
State.create!(name: 'Texas', two_letter_code: 'TX')
State.create!(name: 'Utah', two_letter_code: 'UT')
State.create!(name: 'Vermont', two_letter_code: 'VT')
State.create!(name: 'Virgin Islands', two_letter_code: 'VI')
State.create!(name: 'Virginia', two_letter_code: 'VA')
State.create!(name: 'Washington', two_letter_code: 'WA')
State.create!(name: 'West Virginia', two_letter_code: 'WV')
State.create!(name: 'Wisconsin', two_letter_code: 'WI')
State.create!(name: 'Wyoming', two_letter_code: 'WY')


# Users
 User.create!(id: 0, username: 'shannon', password: "shannon", password_confirmation: "shannon", display_name: 'Shannon Hauck', email: 'shannonmariehauck@gmail.com')

100.times do |i|
  User.create!(username: "username_#{i}", password: "pass_#{i}", password_confirmation: "pass_#{i}", display_name: "User Num #{i}", nickname: "#{i}", email: "useremail_#{i}@example.com")
end

10.times do |i|
  Erg.create!(name: "ERG_name_#{i}")
end

20.times do |i|
  Membership.create!(user_id: "#{i}", erg_id: '7')
end

10.upto(30) do |i|
  Membership.create!(user_id: "#{i}", erg_id: '1')
end

25.upto(45) do |i|
  Membership.create!(user_id: "#{i}", erg_id: '2')
end

30.upto(50) do |i|
  Membership.create!(user_id: "#{i}", erg_id: '3')
end
